:sparkles: Add new component RuleCollab
CollabCodeTech/training-frontend pull request #13
Opened 2020-03-07 20:35 UTC by LuizGMiranda

# What's the issue linked?

Resolve #9 

# Did you test this feature on all browsers?

Yes, tested with all the following browsers:

- [x] Firefox
- [x] Chrome

# Description

Added a new style component to the <hr /> tag to make the line, being able to pass the width and align properties.

2020-03-09 15:48 UTC, MarcoBrunoBR commented
Great!

It is important you add the component in a page I recommend that you use that the page Dashboard. I think that you forgot to make the style.

2020-03-09 17:36 UTC, LuizGMiranda commented
Add component in Dashboard page. It is not necessary make the style.

2020-03-10 10:25 UTC, marcobrunodev requested changes
> Add component on the Dashboard page. It is not necessary to make the style.
You created the style using the properties:
```javascript
RuleCollab.defaultProps = {
  width: "100%",
  align: "left"
};
```
It's a little bad because it leaves the maintenance more complicated. Today the standard is we have all styles of the component into the style.js file. Imagine that other developer to need to use this component and also to need to change width, this person will make by CSS into the context that the component is being used, unfortunately not will work because of the property have more value of the specificity, so her will have that to make a refactoring on component.

Please. Create a styles.js file and add the CSS's component to him.

2020-03-10 10:25 UTC, marcobrunodev commented on src/components/RulerCollab/index.js
> +};
When we use properties to change the style directly we are mixing the layers (CSS and HTML) and this is also a lack of a standard that will make the maintenance harder in the future.

2020-03-14 08:41 UTC, closed without merging

2020-03-15 19:22 UTC, LuizGMiranda commented on src/components/RulerCollab/index.js
> +};
I will create the file style.js passing the 'props', what do you think?

2020-03-15 19:23 UTC, LuizGMiranda commented
I will create the file style.js passing the 'props', what do you think? @MarcoBrunoBR